#!/bin/bash

# delete existing placeholder site
cd /opt/bitnami/apache2
rm -rf htdocs
ln -s /home/bitnami/inzight-www/iNZight htdocs

# configure git
/opt/bitnami/git/bin/git config --global pull.rebase true

# clone new site
cd /home/bitnami
/opt/bitnami/git/bin/git clone https://github.com/iNZightVIT/inzight-www.git

# setup webhook
apt update && apt install -y webhook
# nohup webhook -hooks inzight-www/hooks.json &
cp inzight-www/webhook.service /lib/systemd/system/
cp /lib/systemd/system/webhook.service /etc/systemd/system/webhook.service
chmod 644 /etc/systemd/system/webhook.service
systemctl daemon-reload
sudo systemctl enable webhook
systemctl service start webhook
