library(iNZightPlots)
data("census.at.school.500", package = "iNZight")

pl <- function(x) png(x, width = 719, height = 660, bg = "transparent")

set.seed(15)
pl("plottype_dot.png")
iNZightPlot(rightfoot, data = census.at.school.500[sample(500, 50), ], cex.dotpt = 2.7)
dev.off()
set.seed(15)
pl("plottype_hist.png")
iNZightPlot(rightfoot, data = census.at.school.500[sample(500, 50), ], cex.dotpt = 2.7, plottype = "hist")
dev.off()
pl("plottype_scatter.png")
iNZightPlot(rightfoot, height, data = census.at.school.500[1:200, ], cex.pt = 1.3)
dev.off()
pl("plottype_hex.png")
iNZightPlot(rightfoot, height, data = census.at.school.500, hex.bins = 8, plottype = "hex")
dev.off()
pl("plottype_grid.png")
iNZightPlot(rightfoot, height, data = census.at.school.500, scatter.grid.bins = 10, plottype = "grid")
dev.off()
pl("plottype_bar.png")
iNZightPlot(travel, data = census.at.school.500)
dev.off()
pl("plottype_bar2way.png")
iNZightPlot(travel, gender, data = census.at.school.500)
dev.off()
