name: Update website
on:
  push:
    branches:
      - master
    paths:
      - 'iNZight/**'

jobs:
  update:
    name: Update
    if: "!contains(github.event.head_commit.message, 'skip build')"
    runs-on: ubuntu-latest
    env:
      TZ: "Pacific/Auckland"
    steps:
      - uses: actions/checkout@v2
